### ISSUE TITLE
For Bootstrap 3 theme example, the clear button on the search pane doesn't clear the search filter

### ISSUE THREAD

**Issue by coolblades** [DataTables/SearchPanes#24]
In this example:
https://datatables.net/extensions/searchpanes/examples/styling/bootstrap3.html
say you enter "Ed" in office column and then press the x to clear it, it will not do it
![image](https://user-images.githubusercontent.com/7798211/105519843-ebc85280-5ca7-11eb-97fc-fb40d37b8032.png)

I believe the issue is because search class in the code:
`search: 'col-sm form-control search',`

and in place the code is looking for
`_this.dom.container.find('.' + _this.classes.search)`
or
`_this.dom.container.find(_this.classes.search);`

which is not correct selector string

probably needs to do '.'+_this.classes.search.replace(/ /g, '.')

btw, is there a way to get the current entered search filter with above example get "Ed", I tried api.column(0).search() and gets empty string back, where api is the filter pane table api

**Comment by SandyDatatables** [comment]
Hi @coolblades ,

Thanks for spotting this. I've again raised an issue internally (DD-1847) and Colin will take a look at it soon before I close the issue.

I also noticed that the clear button was still in the disabled state after typing in the searchbox so have fixed that here too.

The searchbox that you see there is actually a custom input element rather than the one that a DataTable would normally use. I'd just use a jquery selector for the input box. Something like `$($('.dtsp-searchPane .search')[1]).val()` seems to work for me on that example.

As a future note, could you please raise any issues that you find/have in the [forum](https://datatables.net/forums/). That's our main way of picking up on bugs as well as providing fixes. It also means that other members of the community that are having similar issues are more likely to find a fix without posting again :)

Thanks again,
Sandy

**Comment by SandyDatatables** [comment]
Colin has had a look now and is happy so I am going to close this now.

**Comment by coolblades** [comment]
Thanks! Will do - the next time I found any potential issue or have a question.
